### ISSUE TITLE
Github/laptop issues

### ISSUE THREAD

**Issue by brookestewart** [nlottig94/EmilyDickinson6#10]
![git](https://cloud.githubusercontent.com/assets/14084707/14518647/3d387f08-01e7-11e6-96fe-5485351bafaa.png)

So this is what's happening with my GitHub. My Git Shell has been broken, and now the desktop client won't work. I tried restarting my computer, but that didn't work. I tried re-adding the repositories, but no luck there either. Any ideas what to do? It was working fine earlier. 
@RJP43 @ebeshero

**Comment by ebeshero** [comment]
@brookestewart Did you recently have your laptop repaired? I remember you'd taken it to be fixed...First, are your local GitHub files still where you stored them before?

You could write to the e-mail address they gave you, or you could try uninstalling and reinstalling the Windows GitHub client. If you do that, it always seems simplest to me to "nuke" the local repo--destroy it utterly and completely (from your trash too) and clone everything fresh. But if you have new files you need to push, copy those somewhere else for safe keeping until you have restored your GitHub. Then you can move them back into your local directory.

@RJP43 may know a solution that doesn't involve nuking the whole thing and starting over, though...

**Comment by RJP43** [comment]
Does the command line still work?

**Comment by ebeshero** [comment]
My guess is that like the other students, she is accessing command line from this Windows client interface.

**Comment by RJP43** [comment]
Which isn't really all that necessary. .. @brookestewart can you find your repo folders (in explorer) on your local computer. And do you know how to open command line from there? If not then yea either nuke or email github I can't do much without seeing it anyway. Or wait till tomorrow and I can see if it's just a client issue or if your whole github is no longer configured

**Comment by brookestewart** [comment]
I did recently have it repaired, but it was working after that. @RJP43 no, command line hasn't been working, remember it wouldn't even open? 
I could try to nuke and reinstall it.

**Comment by ebeshero** [comment]
@brookestewart just remember to set aside somewhere safe any new files you need to commit to the repo. I wonder what happened, but I think some necessary Git configuration file for your client must have gotten corrupted. Sometimes strange things happen in shutting down a computer and maybe a network connection was suddenly cut off and something failed to update... Who knows! But I am sorry it happened. Writing to github support might actually be a good idea--they tend to know what goes wrong in these situations and might have useful pointers for us that we can learn from!

**Comment by brookestewart** [comment]
I'm not sure what happened, but I nuked and reinstalled it and it gave me the same message. However, it let me clone the repo and seems to be working now! Thanks!

**Comment by nlottig94** [comment]
@brookestewart you got everything figured out, right?  I'm going to close this issue.
