### ISSUE TITLE
Bibliography Page

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#15]
@brookestewart 
Here are the entries that need to be on the bibliography page:
- Dickinson, Emily. _The Manuscript Books of Emily Dickinson_. Cambridge, Massachusetts: The Belknap Press of Harvard University Press, 1981.
  Ralph W. Franklin reassembled Emily's fascicle manuscripts in this facsimile edition. Our manuscript images on the site are originally from this source. (Put in Image group)
- Dickinson, Emily. _The Poems of Emily Dickinson, Centenary Edition_. Boston: Little, Brown and Company, 1930. 
  Edited by Martha Dickinson Bianchi and Alfred Leete Hampson. Martha Dickinson Bianchi was Emily's niece. She and her secretary, Alfred Leete Hampson edited Emily's poems in an attempt to make them more readable. For more information on Martha Dickinson Bianchi, please visit her biography page on the Emily Dickinson Museum website.
- Dickinson, Emily. _Letter to Susan Dickinson_. Emily Dickinson Archive.
  The Centenary Edition feature a different version of poem 11 than the one found in Fascicle 16. We had to locate the origianl manuscript written by Emily Dickinson in a letter to her sister-in-law, Susan Dickinson. We found the first page of the manuscript image on the Emily Dickinson Archive website (linked in this entry). We emailed the editor of the website, who then sent us the missing image of the second page.
- Dickinson, Emily. _Atlantic Monthly_. February 1929.
  This is an American magazine that published a version of Emily Dickinson's poem 2 in the February issue in 1929.
- Dickinson, Emily. _Bolts of Melody: New Poems of Emily Dickinson_. New York: Harper and Brothers, 1945.
  Edited by Mabel Loomis Todd and Millicent Todd Bingham. Mabel Loomis Todd was a good friend of Emily and took up publishing her poems in this edition, but did not live to see it completed. Her daughter, Millicent Todd Bingham, finished the work on her mother's behalf. For more information on Mabel Loomis Todd, please visit her biography page on the Emily Dickinson Museum website.
- Dickinson, Emily. _Final Harvest: Emily Dickinson's Poems_. Boston: Little, Brown and Company, 1961.
  Edited by Thomas H. Johnson. As shown in our graph, this edition is the closest representation of Emily's original manuscripts. This edition is the most accurate because literary scholar Thomas H. Johnson returned to Emily's manuscripts, rather than other publisher's editions, to transcribe her poems as closely as possible before publishing them in print. He studied her handwriting in detail, which allowed for great accuracy.
- Dickinson, Emily. _Further Poems of Emily Dickinson_. Boston: Little, Brown and Company, 1929.
  Edited by Martha Dickinson Bianchi and Alfred Leete Hampson.
- Dickinson, Emily. _Poems, Third Series_. Boston: Roberts Brothers, 1896.
  Edited by Mabel Loomis Todd.
- Dickinson, Emily. _Poems, Second Series_. Boston: Roberts Brothers, 1891.
  Edited by Mabel Loomis Todd and T. W. Higginson.
- Dickinson, Emily. _Poems_. Boston: Roberts Brothers, 1890.
  Edited by Mabel Loomis Todd and T. W. Higginson. Thomas Wentworth Higginson was one of Emily's close friends and mentor. He co-edited this collection of her poems with Mabel Loomis Todd (see Bolts of Melody entry) which was published in 1890, just fours years after Emily's death. The editors changed punctuation and word choices in an attempt to make the poems more readable. For more information on Thomas Wentworth Higginson, please visit his biography page on the Emily Dickinson Museum website.
- Dickinson, Emily. _The Complete Poems of Emily Dickinson_. Boston: Little, Brown and Company, 1960.
  Edited by Thomas H Johnson.
- Vendler, Helen. _Dickinson: Selected Poems and Commentaries_. Cambridge, Massachusetts: The Belknap Press of Harvard University Press, 2010.\

I think we also need to credit the Emily Dickinson Archive and where the images came from, so:
- Houghton Library, Harvard University, Cambridge, MA
  Dickinson, Emily, 1830-1886. Poems: Packet III, Fascicle 6. Includes 17 poems, written in ink, ca. 1859. Houghton Library, Harvard University, Cambridge, Mass.
- Emily Dickinson Archive
  http://www.edickinson.org (Letter)

These last two may need switched around to match the bib. style that you're using!!
If you need any other information, let me know!!!

**Comment by brookestewart** [comment]
- [ ] Insert link to our new bibliography page under the dash analysis.
