### ISSUE TITLE
Site ready for grading!

### ISSUE THREAD

**Issue by brookestewart** [nlottig94/EmilyDickinson6#16]
@ebeshero  @ghbondar 
The site is up and ready for grading! Here's what we did this semester:
- Scanned all published versions of the poems from Fascicle 6
- Transcribed and marked up all poems
- Created an SVG graph for percentage of dash reduction for Fascicle 6
- Created network analysis  using XQuery for both Fascicle 16 and 6 to measure how inter-related the variants are between all versions
- Update and add new drop down menu buttons
- Photoshop and image map all images 
- Update and fix XSLT, javascript, and CSS to create a less brittle solution
- Write ups: Overall homepages for both fascicles, overall fascicle homepage, update fascicle 16 information, network analysis for both fascicles, dash analysis (6), overall analysis (6), overall conclusion (6), methodology (update format and complete for 6), added to and update bibliography

As a note, our site is still validated by w3schools! I believe this is everything. As before, there is a more detailed break-down of everything that each of us completed on our [Methodology page](file:///C:/Users/Brooke/Documents/GitHub/EmilyDickinson6/EmilyDickinson6/Web-Files/methodology.html)!

In the future, we plan to keep adding more fascicles and comparing their variations!

**Comment by ebeshero** [comment]
Thanks for your great work, @brookestewart and @nlottig94! We're sending your project evaluation today with lots of comments! You really did a brilliant job, which _also_ means there are some more things you can work on here to improve this for presentation next month and in future.
