### ISSUE TITLE
Project Midterm

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#3]
Todo list:
- [x] Find all poems in manuscripts
- [x] Find all poems in published books already checked out of library
- [x] Scan pages with poems on them
- [x] Find all poems in published books being sent to UPG from other Pitt libraries
- [x] Scan above poems
- [x] Transcribe manuscripts
- [x] Code! Code! Code!
- [ ] Describe image on one letter
- [x] Add new published works to listWit

And more to come!

**Comment by nlottig94** [comment]
@brookestewart @ebeshero @RJP43 
So I am transcribing the first poem of Fascicle 6 right now! (So @brookestewart, this means that you will definitely have to go over my transcriptions to make sure they're right!) But I noticed that the word "Colors" is underlined in the manuscript. I looked up the TEI way on how to mark this, and it's looking like I should use `<hi rend="underline">`. Is this correct?

**Comment by nlottig94** [comment]
@brookestewart @ebeshero @RJP43 
There are also words with quotes around them, such as `"Promoted"`. Should I use `<hi rend="quoted">` and then get rid of the quotes??

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart You have several options to consider very carefully here--based on Dickinson's usage. You're looking really at _her_ markup of her own text! 
- Does the underlining serve to _emphasize_ a word, put stress on it? If so, consider using `<emph rend="underline">`. I tend to reserve `<hi>` for situations where the underlining isn't about emphasis on a word--like when it is used for setting off a book title.
- Do the quotation marks indicate _spoken_ expression by someone? If so, use an element that conveys the quotation of someone speaking. That will be the `<q>` element. You'll want to read more about these options in [Chapter 3 of the TEI Guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COHQHE).

**Comment by nlottig94** [comment]
@ebeshero Yes, it does seem to emphasize a word! I will mark it with `<emph rend="underline">`. And the quotation marks do not correspond to spoken expression; however, I was looking at the TEI website that you gave me and it's pretty much leading me to still use `<q>` elements, but I was thinking that it would be wise to have an `@type` describing why it is in quotes. I'm not entire sure what attribute value to have, though: [`thought` or `emph`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-q.html)?

**Comment by nlottig94** [comment]
@ebeshero and @brookestewart 
So I'm now on poem 2. the Poems3 edition of the poem has a title. Any suggestions about what to do with this?

**Comment by nlottig94** [comment]
@ebeshero @brookestewart 
I've just found single quotes now! Could we use the `<q>` element with an `@rend` to distinguish double quotes and single quotes?

**Comment by ebeshero** [comment]
@nlottig94 Look up the title element in the TEI...And yes I think you understand the use of`@rend`.

**Comment by RJP43** [comment]
@nlottig94 and I think what you are saying is that edition has a title whereas the manuscript and other editions do not .... so just stick the title element into an app wit setup.

**Comment by ebeshero** [comment]
@RJP43 @nlottig94 No--I wasn't saying anything like that! I was just asking you to look up the options for titles in the Guidelines--I had not actually done that myself, but was inviting you to do so!

**Comment by ebeshero** [comment]
@RJP43 @nlottig94 I think you need to use the TEI Header and its `<titleStmt>` here, and you saw this in the XQuery Exercise 2 with the Mitford project. If the poem has an alternative title, you can include it there, like we did with The Melfi vs. Julian. I don't think this needs to affect your list of witnesses.

**Comment by RJP43** [comment]
I think the concern was that [this edition of poem 2](https://github.com/nlottig94/EmilyDickinson6/blob/master/ImageFiles/602/602poems3.jpg) has a title whereas the manuscript and all of the other editions do not have a title ... so I was suggesting that once you investigate the TEI options of title that you could stick the title in the `<app><rdg>` setup

something like this:

`<app><rdg wit="#df6 #CP"></rdg><rdg wit="#poems3"><title>THE WAKING YEAR.</title></rdg></app>`

but if this is something better handled in the TEI Header and its `<titleStmt>` that OK too .... just wanted to clarify what I meant!

**Comment by ebeshero** [comment]
@RJP43 @nlottig94  It's adding complication to your list of reading witnesses, when all you want to do is give this particular document a title. The reading witness doesn't need to be any different than it is for any other poem in the fascicle, since you're referring to the same bundle of manuscripts. So, really, this one just has a title where the others don't. I think in the Dickinson project titleStmt elements, you're giving each poem a designated number in the fascicle, which represents Dickinson's organization. It's okay to give a second `<title>` there for this particular poem! It will be interesting to see if the published editions represent that title.

**Comment by RJP43** [comment]
Oh I was under the impression from your [wiki](https://github.com/nlottig94/EmilyDickinson6/wiki/Colors-&-Tags) that `#poems3` was already an edition with a reading witness ID... sorry was looking from the outside in and got confused... still am a bit but as long as you ( @nlottig94 and @brookestewart ) can make sense of all that then that is all that matters.
