### ISSUE TITLE
Person Names in Poems

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#4]
@brookestewart in Poem 1 Dickinson refers to Pizarro (Francisco Pizarro González, a Spanish conquistador). Do you think we should mark this up in `<persName>` tags just to have it? We don't really need to use it in our research, but if someone else ends up wanting to do something different with it later, then it will already be marked...

**Comment by brookestewart** [comment]
I don't think it would hurt anything! Like you said, it would be helpful for further research.

**Comment by nlottig94** [comment]
@brookestewart this has nothing to do with persNames, but in the `<q>` elements in the fourth poem, do you think it would be characterized as thought: representation of thought, e.g. internal monologue??  Look at [this page](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-q.html) to see what you think will be best in the `@type`.

**Comment by brookestewart** [comment]
@nlottig94 yes, I think that would be the best!

**Comment by nlottig94** [comment]
@brookestewart I also tags countries in `<country>` tags and mountain ranges, such as Alps, in `<geoName>` tags.
