### ISSUE TITLE
Poem 12

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#5]
@brookestewart I know that we discusses having two different XMLs for Poem 12 because it has two different original manuscripts, but I was talking to @RJP43 today, and we were thinking that we could just use the `var0`, `var1`, var2`, etc. for these since not all of the publications state which version it's following.  Does this make sense?

**Comment by nlottig94** [comment]
@ebeshero as I was trying to add `var0`, etc. into the `@wit` in Poem  12, I noticed that our Schematron is firing because anything in the `@wit` is to be only the witnesses in the listWit...is there like an if then statement type thing that we can use here???  I tried to Google it, but had no luck!

**Comment by ebeshero** [comment]
@nlottig94 I don't see your Schematron file. You need to include it in the repository, and it sounds as if you need to modify either it or your list of witnesses to include your encoding of Dickinson's variants. How did you control this in the Dickinson 16 project?

**Comment by nlottig94** [comment]
@brookestewart What I have suggested above might prove to be very hard... @RJP43 could you take a look at the images and what I have so far in the XML for Poem 12?  I'm stuck on line 5 and 6...

**Comment by nlottig94** [comment]
@ebeshero it is in the Dickinson6_InitialXML folder [here](https://github.com/nlottig94/EmilyDickinson6/blob/master/Dickinson6_InitialXML/Schematron2Dickinson.sch).  And we didn't control this in Dickinson 16...So I'm assuming that there will be an issue there as well.

**Comment by ebeshero** [comment]
@nlottig94 I've just made a modification to your Schematron and issued a pull request. I think it'll resolve the problem--let me know.

**Comment by nlottig94** [comment]
REFER TO [THIS ISSUE](https://github.com/nlottig94/EmilyDickinson6/issues/8)
