### ISSUE TITLE
Things that need to be done with Dickinson as a whole

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#9]
- [x] Study @amielnicki's XSLT and see if anything needs changed for Fascicle 6.
- [x] Study @amielnicki's JavaScript file.
- [x] Create one full bibliography page, as well as having individual ones for each poem's images.
- [x] Create new overall Dickinson homepage.
- [x] Create homepage for Dickinson 6.
- [x] Create homepage for Dickinson 16.
- [x] Fix button color of Atlantic Monthly on [Poem 2 of Fascicle 16](http://dickinson16.newtfire.org/1602.html).
- [x] Photoshop and create image-mapping for Fascicle 6.
- [x] Run XSLT over Fascicle 6 poems to create HTML.
- [x] Create SVG graph of dashes for Fascicle 6.
- [x] Create Network Analysis for Fascicle 6.
- [x] Add both Network Analyses to Dickinson site.
- [x] Edit [About page](http://dickinson16.newtfire.org/about.html), [Members page](http://dickinson16.newtfire.org/members.html), [Methodology page](http://dickinson16.newtfire.org/methodology.html), and [Conclusions page](http://dickinson16.newtfire.org/conclusion.html) to work for both last semester and this semester.
- [x] Specify that the line numbers on the HTML mean how many lines are possible in _all_ of the publications of a poem.
- [x] Create tables with show/hide function where variations occur in all poems. (A suggestion from David, that will really make everything easier to read.)

**Comment by nlottig94** [comment]
@brookestewart @nlottig94

**Comment by nlottig94** [comment]
I'm tagging @amielnicki and @blawrence719 just so they can see where Dickinson is going.

**Comment by nlottig94** [comment]
@ebeshero @ghbondar @RJP43 @brookestewart 
We may need (well, probably will) add to this list, but it's just to keep everything clear so it won't get confused in my head!

**Comment by nlottig94** [comment]
@brookestewart I am done photoshopping poems 1-9.  If you could look over the rest of them tonight, so I can photoshop them tomorrow, I would really appreciate it!

**Comment by nlottig94** [comment]
@brookestewart @ebeshero @RJP43 
I just added html pages so we have something to work with when we get there. Also, since my CSS and JavaScript folders will be _outside_ the 6 and 16 folders, how do I go about linking them in the 6 and 16 poems themselves? I know it's got to be super simple, I'm just drawing a blank right now!!

**Comment by RJP43** [comment]
@nlottig94 Where are they sitting in relation to each other? If all of the poems are in a folder that is sitting inside of a folder that is holding another folder with the javascript and CSS you just have to follow the path from the poem to the javascript and css... similar to how you navigate n fetch/command line `../` will take you all the way out to the root directory. From there you can slash into the folder holder the javascript and css then slash to whichever file you want (omitting slash and foldername if no folder holding the javascript and css)... is that helpful?

you can also see how we navigate to our schema ( which sits out in the main directory in a folder ) from each article (which sit inside of a folder that is inside of another folder that is inside of the main directory) ... this is our schema line ***note the slashes and dots**\* `<?xml-model href="../..//webDevelopment/nelsonSchematron.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>` so as you can see from the article we take a two dots to get out of the file and out of the folder holding the articles and another two dots to get out of that folder and back into the main directory then we use the slashes to drop into the right folder (for us webDevelopment) and one more slash to get the right file.

**Comment by nlottig94** [comment]
Thanks @RJP43!!  I'm going to work on this tonight, so I'll try it then!  If I have any issues, I'll ask you in the morning!

**Comment by nlottig94** [comment]
Leaving this here for myself as I'm doing image mapping.
http://imagemap-generator.dariodomi.de/

**Comment by nlottig94** [comment]
@ebeshero @RJP43 @ghbondar @brookestewart 
We have our first XML to HTML webpage for Fascicle 6!!  I've fixed the XSLT and CSS!  I still need to do the JavaScript, but I have to go to work.

**Comment by ebeshero** [comment]
Yay! Post a link so we can view it from GitHub?

**Comment by nlottig94** [comment]
@ebeshero here's the [link](http://htmlpreview.github.io/?https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/6/601.html).
Sorry it took me so long to respond!  I'm going to look at the JavaScript now so I can have it fully functioning!!

**Comment by ebeshero** [comment]
Looks great so far, @nlottig94 !

**Comment by nlottig94** [comment]
The JavaScript is finished!!

**Comment by nlottig94** [comment]
@ebeshero 
So I'm trying to do what [David suggested](https://github.com/ebeshero/EmilyDickinson16/issues/31) with the tables (scroll to where his comments are), but I'm having issues...Here is my [XSLT](https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/6/xml/dickinson6Experiment.xsl).  Sorry it's a bit messy!!  And here's my [output HTML](https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/6/601Experiement.html).  Okay, I had the CSS working when it wasn't on GitHub, so if you pull the changes in and open it, you should see what's going wrong.
I think I know what's going wrong, but every time I try to fix it, it doesn't seem to work...Any suggestions???

**Comment by nlottig94** [comment]
Oh!  And I also know that I need my `span`s _inside_ the `tr`. But that's an easy fix after I figure out how to output the tables...

**Comment by ebeshero** [comment]
@nlottig94 Aha! I spotted the error: It's really tiny, in your CSS line: You have Web-files and it needs to be Web-Files (both words capitalized). Was that the problem you wanted me to see if I could fix?

**Comment by nlottig94** [comment]
Thanks @ebeshero!  That's not the issue, though, if you look at the tables, it's outputting, that is the issue I need to fix.  And I want there not to be a table when there aren't any `app`s...Is that understandable? If not, let me know!

**Comment by nlottig94** [comment]
@ebeshero 
When creating an SVG from XSLT, is there any restriction of how much content a `g` element can hold?  I'm having an issue where oxygen is saying that I have to close a `g` element right in the middle of what needs to be held in it...
[Here's the link to my XSLT](https://github.com/nlottig94/EmilyDickinson6/blob/master/SVG/xslt_to_SVG-Final.xsl)

**Comment by ebeshero** [comment]
@nlottig94 Sorry--I wondered about those tables but I wasn't sure what you were aiming to do! It struck me there's a lot of repetition of the same variants and a lot of empty table cells, but I figured you'd be using CSS and JavaScriot to toggle their display property, so they could be hidden without taking up space. I'm just looking from my iPad right now, but I see what's making your XSLT to  output empty table elements. It is because you have set those elements **outside** your XSL conditional statements, so they will always be output, but will have empty content, which seems to be what is happening.

You have set a new table element for every line, if I am reading this right. If you don't want a table in the absence of an `<app>` element, you need to write a conditional statement to prevent it.

I am not really sure what you are trying to do with these tables. One thing you could try is to output the _entire line_ of a given edition of the poem inside each table row, and wrap the variant portions of the line in a span that you color with CSS. Then, whenever you have an `<app>` inside a line, you output that full line with how it appears in every edition. Would that make this legible for the reader? You could then toggle the display of the table rows off and on to expand and contract the poem as it appears on screen. 

Does that help?

**Comment by ebeshero** [comment]
@nlottig94 As for the XSLT to SVG, no there is no limit to how much goes into a `<g>` element, so long as the contents are well-formed! I think there is an element that isn't properly closed somewhere...I'll take a look more closely...

**Comment by ebeshero** [comment]
@nlottig94 ....and yes, that's it: You have several extra closing `</xsl:for-each>` tags in your XSLT and that was making your file not be well-formed. There will be one other problem once you clear that up: see my line comments: https://github.com/nlottig94/EmilyDickinson6/commit/8489d7ef2d36cd2dcd4198f82c11076bc42b8f86

**Comment by nlottig94** [comment]
@ebeshero 
So, as I've mentioned above, I was trying to output tables as the lines, so we could see the variations in a more organized way.  I _did_ succeed in doing this; however, it's not valid in HTML (I get the red angry square in oxygen!).  Here is my [XSLT for the HTML](https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/6/xml/Dickinson6Experiment2.xsl).   Here is my [output HTML](http://htmlpreview.github.io/?https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/6/601Experiment2.html).
The show/hide function works, but I don't really like how it is outputting the tables, also, I had to create a literal line break in the variant `table cells because I couldn't get it to output the way I wanted it to. 
Could you have a look at this @ebeshero and see if you can figure it out? (Since I can't figure out why the output HTML isn't valid?

**Comment by nlottig94** [comment]
@brookestewart @ebeshero @RJP43 @ghbondar 
I slightly changed our newest XSLT so it would work for Fascicle 16 and ran all of the poems to get new HTML pages for 16!  Right now all of the poems (Fascicle 16 and 6) are up and running on the [Dickinson site](http://dickinson16.newtfire.org/)!!!  Check it out!!!
I have to fix some links and some drop-down menus, but other than that, new write-ups, and a network analysis for Fascicle 6, Dickinson is almost complete!!

**Comment by ebeshero** [comment]
Great work, @nlottig94 ! The image mapping looks good too, @brookestewart ! Looks like your intro page to Fascicle 6 isn't loading its image?

**Comment by nlottig94** [comment]
@ebeshero
The home pages aren't finished yet.  I need to make write ups for each!  It'll be up soon!

**Comment by brookestewart** [comment]
@nlottig94 I have the fascicle pages, bibliography, and dash analysis done. I just need to finish the fascicle 6 analysis and conclusion. I went to update the dash analysis for 16, but I need you to change the permissions, it won't even let me delete it. It's dash.html inside the 16 folder. I have to get a few hours of sleep, and I'll try to finish as much as possible in the morning, but I probably won't be done before you leave for work. I didn't want to text you now and wake you up!

Update: I was on a roll, so I went and did the analysis page. I just need to do the conclusion. (and update the dash 16 page!)

**Comment by nlottig94** [comment]
@brookestewart Okay..The permissions were fine on the dash.html inside of the 16 folder...I'll push what you have in GitHub to the site. I'm working on the methodology now. I will make sure I'm finished with it before work. Whenever you're finished with the conclusion page, set up a new issue and tag Dr. B and Greg in it and try to state everything we did. Also, mention that I will try to create a page that describes in detail what our new XSLTs do. I'm going to run the site over the w3schools thing right now too because all we are adding is text, so nothing should be a problem.

**Comment by nlottig94** [comment]
@brookestewart as an update, I just ran the site over the w3schools validator and we're all good!!  Make sure you mention that on the comment as well!!!

**Comment by nlottig94** [comment]
@brookestewart I am finished with the Methodology!!!  I'm going to insert the info about what the line numbers actually mean in the poems pages then I'm finished for now. There are a few minor things to do, but I can fix those any time before the conference. Also, I noticed that we didn't get to describe the image on the one poem to Susan. You can mention this in the things we didn't get to do, but we can have it done before the conference as well. Just remember to post that issue for Dr. B!  Good luck!
